// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Errors
export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

// Board
export const GET_BOARD = 'GET_BOARD';
export const GET_BOARD_BY_ID = 'GET_BOARD_BY_ID';
export const CLEAR_BOARD = 'CLEAR_BOARD';

export const SET_TASK_IN_SAME_COLUMN = 'SET_TASK_IN_SAME_COLUMN';
export const SET_TASK_IN_NEW_COLUMN = 'SET_TASK_IN_NEW_COLUMN';
export const UPDATE_EXISTING_TASK = 'UPDATE_EXISTING_TASK';
export const CREATE_NEW_TASK = 'CREATE_NEW_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const SET_COLUMN_TITLE = 'SET_COLUMN_TITLE';
export const CREATE_NEW_COLUMN = 'CREATE_NEW_COLUMN';
export const DELETE_COLUMN = 'DELETE_COLUMN';

export const SET_COLUMN_ORDER = 'SET_COLUMN_ORDER';

// Current user's projects
export const GET_CURRENT_USERS_PROJECTS = 'GET_CURRENT_USERS_PROJECTS';
export const SET_PROJECTS_NAME = 'SET_PROJECTS_NAME';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ADD_USER_TO_PROJECT = 'ADD_USER_TO_PROJECT';
export const ADD_USER_ALREADY_EXISTS = 'ADD_USER_ALREADY_EXISTS';

// Project
// export const SET_PROJECT_DATA = 'SET_PROJECT_DATA';
export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT';
// export const CLEAR_PROJECT = 'CLEAR_PROJECT';
// export const SET_PROJECT_NAME = 'SET_PROJECT_NAME';

export const SET_CURRENT_PROJECT_DATA = 'SET_CURRENT_PROJECT_DATA';
export const CLEAR_CURRENT_PROJECT = 'CLEAR_CURRENT_PROJECT';
export const SET_CURRENT_PROJECT_NAME = 'SET_CURRENT_PROJECT_NAME';
